<InspirationalVideos>:
    name: "InspirationalVideos" 
	on_pre_enter: root.callback()
    canvas.before:
        Color:
            rgba: 0.592, 0.741, 0.969, 1
        Rectangle:
            pos: self.pos
            size: self.size

	BoxLayout:
		pos: 0, 100
		size_hint: 0.8, 0.8
		orientation:  'vertical'
	
	Button:
		text: 'Back'
		on_press:
			root.manager.current = 'GetInspired'
		size_hint: 0.16, 0.1
		pos: 0, 0
		
		background_color: 0.18, 0.5, 0.92, 1