
<LeaderBoard>:
    name: "LeaderBoard"
    FloatLayout:
        HeaderWidget:
            size_hint_y: None
            height: 50
            pos_hint: {"x": 0.9, "y": 0.9}
    Label:
        text: 'This page is still in the development phase.'
    Button:
        text: 'Back'
        size_hint: 0.16, 0.1
        pos: 0, 0
        on_press:
            root.manager.current = 'GetRewarded'