<NewYorkState>
    canvas.before:
        Color:
            rgba: 0.592, 0.741, 0.969, 1
        Rectangle:
            pos: self.pos
            size: self.size

    BoxLayout:
        pos: 55, 700
        size_hint: 0.8, 0.06
        Label:
            text: 'Susquehanna River'
            pos: self.pos
            size: self.size
            color: 'black'
            background_color: 0.4196, 0.7922, 0.9569, 1
    
    BoxLayout:
        pos: 55, 680
        size_hint: 0.8, 0.06
        Label:
            text: '• Toxic metals, cadmium, chromium, copper, nickel, and zinc'
            pos: 55, 710
            size: self.size
            color: 'black'
            background_color: 0.4196, 0.7922, 0.9569, 1
    
    BoxLayout:
        pos: 55, 660
        size_hint: 0.8, 0.06
        Label:
            text: '• Nitrogen and phosphorus pollution'
            pos: 55, 690
            color: 'black'
            size: self.size
            background_color: 0.4196, 0.7922, 0.9569, 1
            
    BoxLayout:
        pos: 55, 640
        size_hint: 0.8, 0.06
        Label:
            text: '• Snakehead fish is invasive'
            pos: 55, 670
            color: 'black'
            size: self.size
            background_color: 0.4196, 0.7922, 0.9569, 1

    BoxLayout:
        pos: 55, 550
        size_hint: 0.8, 0.06
        Label:
            text: 'Elmira toxins'
            pos: self.pos
            size: self.size
            color: 'black'
            background_color: 0.4196, 0.7922, 0.9569, 1
    
    BoxLayout:
        pos: 55, 530
        size_hint: 0.8, 0.06
        Label:
            text: '• Contaminated soil'
            background_color: 0.4196, 0.7922, 0.9569, 1
            pos: 55, 560
            color: 'black'
            size: self.size
    
    BoxLayout:
        pos: 55, 510
        size_hint: 0.8, 0.06
        Label:
            text: '• Coldbrook Creek with contaminated soil'
            pos: 55, 540
            color: 'black'
            size: self.size
            background_color: 0.4196, 0.7922, 0.9569, 1
            
    BoxLayout:
        pos: 55, 490
        size_hint: 0.8, 0.06
        Label:
            text: '• Polychlorinated biphenyls'
            background_color: 0.4196, 0.7922, 0.9569, 1
            pos: 55, 520
            color: 'black'
            size: self.size

    BoxLayout:
        pos: 55, 400
        size_hint: 0.8, 0.06
        Label:
            text: 'Onondaga Lake'
            pos: self.pos
            color: 'black'
            size: self.size
            background_color: 0.4196, 0.7922, 0.9569, 1
    
    BoxLayout:
        pos: 55, 380
        size_hint: 0.8, 0.06
        Label:
            text: '• Ammonia and phosphorus in sewage'
            background_color: 0.4196, 0.7922, 0.9569, 1
            pos: 55, 410
            color: 'black'
            size: self.size
    
    BoxLayout:
        pos: 55, 360
        size_hint: 0.8, 0.06
        Label:
            text: '• Impacts on fish migration and reproduction'
            pos: 55, 390
            size: self.size
            color: 'black'
            background_color: 0.4196, 0.7922, 0.9569, 1
            
    BoxLayout:
        pos: 55, 340
        size_hint: 0.8, 0.06
        Label:
            text: '• Algal blooms and poor water clarity'
            background_color: 0.4196, 0.7922, 0.9569, 1
            pos: 55, 370
            color: 'black'
            size: self.size
            
    BoxLayout:
        pos: 55, 320
        size_hint: 0.8, 0.06
        Label:
            text: '• Decreased oxygen levels'
            background_color: 0.4196, 0.7922, 0.9569, 1
            pos: 55, 350
            color: 'black'
            size: self.size
    
    Button:
        text: 'Back'
        pos: 0,0
        size_hint: 0.16, 0.1
        on_press:
            root.manager.current = 'GetInformed'
        background_color: 0.4196, 0.7922, 0.9569, 1