<SaveTheEarth>:
    FloatLayout:
        HeaderWidget:
            size_hint_y: None
            height: 50
            pos_hint: {"x": 0.9, "y": 0.9}
    Button:
        font_size: 40
        size: 175, 75
        color: 0,1,0,1

    Widgets:
        Button: 
            pos: root.x, root.top - self.hieght 
            text: "Kivy"
    
        Button:
            pos: 170,0
            text: "Tutorials"