<Video1>:
    canvas.before:
        Color:
            rgba: 0.8, 1, 0.698, 1
        Rectangle:
            pos: self.pos
            size: self.size
    name: "Video1"
    VideoPlayer:
        source: root.Video_URL
        state: 'play'
        options: {'eos': 'stop'}
        allow_fullscreen: True

    Button:
		text: 'Back'
		on_press:
			root.manager.current = 'InspirationalVideos'
		size_hint: 0.16, 0.1 
		pos: 0, 0
		
		background_color: 0.0, 0.447, 0.071, 1